### ISSUE TITLE
ERROR ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by gdesor** [Firelods/MyDaciaEnhanced#28]
Hello, I just installed your software, and I successfully reached the homepage http://localhost:4200.

But:
1/ the clicks have no effect. on homepage/refresh/gear/login
2/ What is the login and password? I don't see any configuration file. Is it the Dacia account?

When I launch "ng serve", it give me :
`G02801: Angular detected that `HttpClient` is not configured to use `fetch` APIs. It's strongly recommended to enable `fetch` for applications that use Server-Side Rendering for better performance and compatibility. To enable `fetch`, add the `withFetch()` to the `provideHttpClient()` call at the root of the application.`

When I reach the homepage, I get : 
```
ERROR ReferenceError: localStorage is not defined
    at canActivate (/var/www/html/MyDaciaEnhanced/front/src/app/guard/auth.guard.ts:24:19)
    at eval (/var/www/html/MyDaciaEnhanced/front/node_modules/@angular/router/fesm2022/router.mjs:3287:53)
    at Observable2.eval (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/observable/defer.js:5:15)
    at Observable2._trySubscribe (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/Observable.js:34:21)
    at eval (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/Observable.js:28:115)
    at errorContext (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/util/errorContext.js:24:5)
    at Observable2.subscribe (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/Observable.js:23:7)
    at eval (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/operators/take.js:7:12)
    at OperatorSubscriber.eval (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/util/lift.js:10:18)
    at eval (/var/www/html/MyDaciaEnhanced/front/node_modules/rxjs/dist/esm/internal/Observable.js:28:44)
```

I tried with Firefox 129.0.2 and chrome 128.0.6613.84 on Linux.

Thank you for the help you're surely going to provide me.

**Comment by Firelods** [comment]
Thank you for your inquiry.

Regrettably, the front-end development of this project is incomplete due to a change in project priorities approximately six months ago.

However, the back-end is fully functional, and we welcome your participation in the project.

If you have any feedback or advice that could contribute to the completion of this project, I would be delighted to receive it.

The login/password to use is the one for your myrenault account, which you use in the official Dacia app.

Thank you for your understanding.
